MONGODB_URL = "mongodb://localhost:27017/"
DataBaseName = "CampusFoodDeliverySystem"
RestaurantCollectionName = "Restaurants"
RatingsCollectionName = "Ratings"
RestaurantMenuCollectionName = "Menu"
UsersCollectionName = "User"